Add travis builds with custom depency versions
They are mostly focused at making sure the minimum versions work.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,14 +1,50 @@
 env:
- - CABALVER=1.18 GHCVER=7.6.3
- - CABALVER=1.18 GHCVER=7.8.4
  - CABALVER=1.22 GHCVER=7.10.2
+ - CABALVER=1.18 GHCVER=7.8.4
+ - CABALVER=1.18 GHCVER=7.6.3
+ # Depency set frozen to be in sync with Debian Jessie Haskell packages.
+ # Dependencies not present in Debian use the cabal solver. This includes
+ # direct dependencies too.
+ - CUSTOMSET=jessie
+ # Minimum dependencies for direct depencies and Depency set frozen to be in
+ # sync with Debian Jessie Haskell packages.  Dependencies not present in
+ # Debian use the cabal solver.
+ - CUSTOMSET=jessie-minimum
  - CABALVER=head GHCVER=head
 
 matrix:
   allow_failures:
-   - env: CABALVER=head GHCVER=head
+   - env:
+     # Direct dependencies set to the minimum bounds. Transitive depencies use
+     # cabal solver.
+     - CUSTOMSET=minimum
+     - CABALVER=head GHCVER=head
 
 before_install:
+ - case "$CUSTOMSET" in
+    "") ;;
+
+    "jessie")
+      export CABALVER=1.20 ;
+      export GHCVER=7.6.3 ;
+      mv cabal-deb.config cabal.config ;;
+
+    "minimum")
+      export CABALVER=1.20 ;
+      export GHCVER=7.6.3 ;
+      mv cabal-min.config cabal.config ;;
+
+    "jessie-minimum")
+      export CABALVER=1.20 ;
+      export GHCVER=7.6.3 ;
+      cat cabal-deb.config cabal-min.config > cabal.config ;;
+
+    *)
+      export GHCVER=unknown ;
+      echo "unknown/invalid depency set requested" ;
+      exit 1 ;;
+    esac
+
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
